name: physioex
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.0=py310h06a4308_0
  - python=3.10.0=h12debd9_5
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.2.0
    - babel==2.15.0
    - black==24.4.2
    - boto3==1.34.119
    - botocore==1.34.119
    - braindecode==0.8.1
    - captum==0.7.0
    - certifi==2024.6.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - colorama==0.4.6
    - comm==0.2.2
    - contourpy==1.2.1
    - cycler==0.12.1
    - debugpy==1.8.1
    - decorator==5.1.1
    - dirhash==0.4.0
    - docker-pycreds==0.4.0
    - docstring-inheritance==2.2.0
    - einops==0.8.0
    - exceptiongroup==1.2.1
    - executing==2.0.1
    - filelock==3.14.0
    - fonttools==4.53.0
    - frozenlist==1.4.1
    - fsspec==2024.6.0
    - ghp-import==2.1.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - h5py==3.11.0
    - idna==3.7
    - ipykernel==6.29.4
    - ipython==8.25.0
    - ipywidgets==8.1.3
    - isort==5.13.2
    - jedi==0.19.1
    - jinja2==3.1.4
    - jmespath==1.0.1
    - joblib==1.4.2
    - jupyter-client==8.6.2
    - jupyter-core==5.7.2
    - jupyterlab-widgets==3.0.11
    - kiwisolver==1.4.5
    - lazy-loader==0.4
    - lightning==2.2.5
    - lightning-utilities==0.11.2
    - loguru==0.7.2
    - markdown==3.6
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.0
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mergedeep==1.3.4
    - mkdocs==1.6.0
    - mkdocs-autorefs==1.0.1
    - mkdocs-get-deps==0.2.0
    - mkdocs-material==9.5.25
    - mkdocs-material-extensions==1.3.1
    - mkdocstrings==0.25.1
    - mne==1.7.0
    - mpmath==1.3.0
    - multidict==6.0.5
    - mypy-extensions==1.0.0
    - nest-asyncio==1.6.0
    - networkx==3.3
    - npy-append-array==0.9.16
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.40
    - nvidia-nvtx-cu12==12.1.105
    - packaging==24.0
    - paginate==0.5.6
    - pandas==2.2.2
    - parso==0.8.4
    - pathspec==0.12.1
    - pexpect==4.9.0
    - pillow==10.3.0
    - platformdirs==4.2.2
    - pooch==1.8.1
    - prompt-toolkit==3.0.46
    - protobuf==4.25.3
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.22
    - pygments==2.18.0
    - pymdown-extensions==10.8.1
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.2.5
    - pytorch-metric-learning==2.5.0
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyyaml-env-tag==0.1
    - pyzmq==26.0.3
    - regex==2024.5.15
    - requests==2.32.3
    - rich==13.7.1
    - s3transfer==0.10.1
    - scantree==0.0.2
    - scikit-learn==1.5.0
    - scipy==1.13.1
    - seaborn==0.13.2
    - sentry-sdk==2.4.0
    - setproctitle==1.3.3
    - six==1.16.0
    - skorch==1.0.0
    - smmap==5.0.1
    - soundfile==0.12.1
    - stack-data==0.6.3
    - sympy==1.12.1
    - tabulate==0.9.0
    - threadpoolctl==3.5.0
    - tokenize-rt==5.2.0
    - tomli==2.0.1
    - torch==2.3.0
    - torchaudio==2.3.0
    - torchinfo==1.8.0
    - torchmetrics==1.4.0.post0
    - tornado==6.4
    - tqdm==4.66.4
    - traitlets==5.14.3
    - triton==2.3.0
    - typing==3.7.4.3
    - typing-extensions==4.12.1
    - tzdata==2024.1
    - urllib3==2.2.1
    - wandb==0.17.0
    - watchdog==4.0.1
    - wcwidth==0.2.13
    - wfdb==4.1.2
    - widgetsnbextension==4.0.11
    - xlrd==2.0.1
    - yarl==1.9.4
prefix: /esat/biomeddata/ggagliar/miniconda3/envs/physioex
